In [1]:
import os
import sys

os.chdir("..")
sys.path.append(os.getcwd())

from experiment_runner import run_all_experiments
from analysis import *

In [2]:
df = load_results("./results/exp1_hparams")
summary = summarize(df, ["model", "lr", "weight_decay", "dropout", "batch_size"])
config_keys = ["model", "lr", "weight_decay", "dropout", "batch_size"]

best_cnn = get_best_configs(summary, top_k=10, model="cnn", metric="mean_test_macro_f1")
best_cnn_dict = best_cnn.iloc[0][config_keys].to_dict()
best_resnet = get_best_configs(summary, top_k=10, model="resnet18", metric="mean_test_macro_f1")
best_resnet_dict = best_resnet.iloc[0][config_keys].to_dict()

In [3]:
best_cnn

,model,lr,weight_decay,dropout,batch_size,mean_acc,std_acc,mean_f1,std_f1,mean_val_acc,mean_val_f1,mean_test_macro_f1,std_test_macro_f1
5,cnn,0.000461,0.000036,0.3,64,0.822656,0.001902,0.822423,0.001787,0.825563,0.825290,0.822423,0.001787
11,cnn,0.001075,0.000048,0.3,64,0.822159,0.000783,0.822052,0.000630,0.825293,0.825150,0.822052,0.000630
9,cnn,0.000794,0.000022,0.3,64,0.822148,0.000964,0.821934,0.001130,0.825426,0.825110,0.821934,0.001130
16,cnn,0.001758,0.000356,0.3,128,0.821956,0.001897,0.821673,0.001947,0.825604,0.825268,0.821673,0.001947
6,cnn,0.000482,0.000035,0.3,64,0.821748,0.001374,0.821478,0.001375,0.825019,0.824701,0.821478,0.001375
14,cnn,0.001224,0.000226,0.3,64,0.821048,0.000888,0.820927,0.000929,0.824752,0.824573,0.820927,0.000929
8,cnn,0.000675,0.000270,0.5,64,0.820911,0.001165,0.820782,0.001100,0.824063,0.823834,0.820782,0.001100
12,cnn,0.001098,0.000012,0.3,64,0.820926,0.000889,0.820712,0.000816,0.824256,0.824002,0.820712,0.000816
13,cnn,0.001196,0.000118,0.5,64,0.820700,0.000426,0.820536,0.000518,0.823530,0.823307,0.820536,0.000518
15,cnn,0.001546,0.000063,0.3,64,0.820559,0.000656,0.820332,0.000715,0.824496,0.824191,0.820332,0.000715

In [4]:
best_resnet

,model,lr,weight_decay,dropout,batch_size,mean_acc,std_acc,mean_f1,std_f1,mean_val_acc,mean_val_f1,mean_test_macro_f1,std_test_macro_f1
27,resnet18,0.000043,0.000003,0.3,64,0.898759,0.000558,0.898682,0.000527,0.899893,0.899769,0.898682,0.000527
31,resnet18,0.000116,0.000092,0.1,64,0.898415,0.000934,0.898353,0.000914,0.899500,0.899420,0.898353,0.000914
28,resnet18,0.000045,0.000030,0.1,64,0.898407,0.000933,0.898280,0.001036,0.899815,0.899635,0.898280,0.001036
25,resnet18,0.000028,0.000145,0.1,64,0.898063,0.000267,0.897953,0.000218,0.899511,0.899328,0.897953,0.000218
24,resnet18,0.000028,0.000004,0.3,64,0.896426,0.000679,0.896360,0.000649,0.898289,0.898171,0.896360,0.000649
30,resnet18,0.000104,0.000016,0.0,64,0.891870,0.007477,0.891813,0.007439,0.893481,0.893356,0.891813,0.007439
26,resnet18,0.000041,0.000295,0.0,128,0.891189,0.007739,0.890950,0.007849,0.892848,0.892549,0.890950,0.007849
29,resnet18,0.000073,0.000002,0.3,64,0.889930,0.003731,0.889955,0.003642,0.891611,0.891585,0.889955,0.003642
23,resnet18,0.000017,0.000015,0.3,64,0.887959,0.000514,0.887759,0.000486,0.889396,0.889134,0.887759,0.000486
20,resnet18,0.000013,0.000150,0.0,64,0.886704,0.000421,0.886548,0.000437,0.888633,0.888426,0.886548,0.000437

In [5]:
base_config = [best_cnn_dict, best_resnet_dict]

In [6]:
def augmentation_experiments(base_config):
    experiments = []

    for single_config in base_config:
        for aug in [False, True]:
            for mix in [None, "mixup", "cutmix", "both"]:

                config = single_config.copy()

                config["augmentation"] = aug
                config["mix_type"] = mix


                experiments.append(config)

    return experiments

In [7]:
configs = augmentation_experiments(base_config)

In [ ]:
run_all_experiments(
    folder="exp2_aug",
    configs_list=configs
)

Seed: 0, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": null}
Epoch 1: train=1.6569, val=1.4467, acc=0.5612
Epoch 2: train=1.4303, val=1.3093, acc=0.6313
Epoch 3: train=1.3339, val=1.2591, acc=0.6535
Epoch 4: train=1.2614, val=1.1920, acc=0.6913
Epoch 5: train=1.2056, val=1.1476, acc=0.7087
Epoch 6: train=1.1574, val=1.1494, acc=0.7085
Epoch 7: train=1.1116, val=1.0946, acc=0.7353
Epoch 8: train=1.0727, val=1.0753, acc=0.7419
Epoch 9: train=1.0375, val=1.0964, acc=0.7379
Epoch 10: train=1.0003, val=1.0717, acc=0.7495
Epoch 11: train=0.9707, val=1.0545, acc=0.7579
Epoch 12: train=0.9392, val=1.0493, acc=0.7620
Epoch 13: train=0.9123, val=1.0506, acc=0.7629
Epoch 14: train=0.8825, val=1.0433, acc=0.7653
Epoch 15: train=0.8561, val=1.0586, acc=0.7654
Epoch 16: train=0.8301, val=1.0558, acc=0.7665
Epoch 17: train=0.8059, val=1.0799, acc=0.7611
Epoch 18: train=0.7836, val=1.0653, acc=0.7656
Epoch 19: train=0.7626, val=1.0848, acc=0.7676
Seed: 1, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": null}
Epoch 1: train=1.6628, val=1.4398, acc=0.5642
Epoch 2: train=1.4389, val=1.3252, acc=0.6225
Epoch 3: train=1.3398, val=1.2609, acc=0.6559
Epoch 4: train=1.2703, val=1.2074, acc=0.6822
Epoch 5: train=1.2119, val=1.1563, acc=0.7043
Epoch 6: train=1.1647, val=1.1256, acc=0.7216
Epoch 7: train=1.1211, val=1.1128, acc=0.7244
Epoch 8: train=1.0810, val=1.0878, acc=0.7404
Epoch 9: train=1.0461, val=1.1050, acc=0.7344
Epoch 10: train=1.0122, val=1.0753, acc=0.7464
Epoch 11: train=0.9776, val=1.0634, acc=0.7543
Epoch 12: train=0.9474, val=1.0709, acc=0.7573
Epoch 13: train=0.9168, val=1.0600, acc=0.7577
Epoch 14: train=0.8876, val=1.0546, acc=0.7646
Epoch 15: train=0.8593, val=1.0561, acc=0.7642
Epoch 16: train=0.8346, val=1.0497, acc=0.7664
Epoch 17: train=0.8088, val=1.1087, acc=0.7546
Epoch 18: train=0.7871, val=1.0693, acc=0.7689
Epoch 19: train=0.7660, val=1.0852, acc=0.7630
Epoch 20: train=0.7472, val=1.0796, acc=0.7697
Epoch 21: train=0.7318, val=1.0886, acc=0.7649
Seed: 2, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": null}
Epoch 1: train=1.6418, val=1.4206, acc=0.5772
Epoch 2: train=1.4277, val=1.2969, acc=0.6368
Epoch 3: train=1.3273, val=1.2544, acc=0.6550
Epoch 4: train=1.2580, val=1.1976, acc=0.6866
Epoch 5: train=1.2028, val=1.1592, acc=0.7027
Epoch 6: train=1.1545, val=1.1138, acc=0.7256
Epoch 7: train=1.1113, val=1.1020, acc=0.7322
Epoch 8: train=1.0739, val=1.0742, acc=0.7449
Epoch 9: train=1.0344, val=1.0637, acc=0.7489
Epoch 10: train=1.0015, val=1.0762, acc=0.7468
Epoch 11: train=0.9670, val=1.0591, acc=0.7589
Epoch 12: train=0.9367, val=1.0463, acc=0.7623
Epoch 13: train=0.9068, val=1.0568, acc=0.7621
Epoch 14: train=0.8784, val=1.0734, acc=0.7575
Epoch 15: train=0.8518, val=1.0608, acc=0.7645
Epoch 16: train=0.8248, val=1.0618, acc=0.7664
Epoch 17: train=0.8002, val=1.0624, acc=0.7688
Seed: 0, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "mixup"}
Epoch 1: train=1.9537, val=1.5177, acc=0.5478
Epoch 2: train=1.8166, val=1.4412, acc=0.5883
Epoch 3: train=1.7685, val=1.3621, acc=0.6277
Epoch 4: train=1.7189, val=1.3087, acc=0.6416
Epoch 5: train=1.6857, val=1.2542, acc=0.6709
Epoch 6: train=1.6785, val=1.2156, acc=0.6923
Epoch 7: train=1.6498, val=1.2067, acc=0.7030
Epoch 8: train=1.6256, val=1.1767, acc=0.7143
Epoch 9: train=1.6046, val=1.1549, acc=0.7281
Epoch 10: train=1.6002, val=1.1652, acc=0.7265
Epoch 11: train=1.5808, val=1.1234, acc=0.7407
Epoch 12: train=1.5796, val=1.1050, acc=0.7468
Epoch 13: train=1.5573, val=1.1029, acc=0.7535
Epoch 14: train=1.5425, val=1.1013, acc=0.7439
Epoch 15: train=1.5277, val=1.0920, acc=0.7533
Epoch 16: train=1.5257, val=1.0729, acc=0.7617
Epoch 17: train=1.5124, val=1.0475, acc=0.7648
Epoch 18: train=1.4993, val=1.0651, acc=0.7658
Epoch 19: train=1.4901, val=1.0546, acc=0.7656
Epoch 20: train=1.4849, val=1.0673, acc=0.7632
Epoch 21: train=1.4727, val=1.0748, acc=0.7660
Epoch 22: train=1.4664, val=1.0770, acc=0.7665
Seed: 1, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "mixup"}
Epoch 1: train=1.9568, val=1.5499, acc=0.5426
Epoch 2: train=1.8270, val=1.4315, acc=0.5822
Epoch 3: train=1.7601, val=1.3561, acc=0.6283
Epoch 4: train=1.7361, val=1.3138, acc=0.6550
Epoch 5: train=1.7047, val=1.2680, acc=0.6761
Epoch 6: train=1.6702, val=1.2250, acc=0.6869
Epoch 7: train=1.6578, val=1.2163, acc=0.6949
Epoch 8: train=1.6263, val=1.1549, acc=0.7224
Epoch 9: train=1.6021, val=1.1720, acc=0.7159
Epoch 10: train=1.5982, val=1.1567, acc=0.7320
Epoch 11: train=1.5822, val=1.1374, acc=0.7411
Epoch 12: train=1.5615, val=1.0912, acc=0.7446
Epoch 13: train=1.5474, val=1.0980, acc=0.7549
Epoch 14: train=1.5381, val=1.0807, acc=0.7556
Epoch 15: train=1.5348, val=1.0945, acc=0.7567
Epoch 16: train=1.5299, val=1.0634, acc=0.7666
Epoch 17: train=1.5098, val=1.0484, acc=0.7650
Epoch 18: train=1.5165, val=1.0847, acc=0.7603
Epoch 19: train=1.4984, val=1.0493, acc=0.7699
Epoch 20: train=1.4772, val=1.0550, acc=0.7725
Epoch 21: train=1.4702, val=1.0366, acc=0.7738
Epoch 22: train=1.4688, val=1.0922, acc=0.7676
Epoch 23: train=1.4580, val=1.0616, acc=0.7689
Epoch 24: train=1.4484, val=1.0366, acc=0.7762
Epoch 25: train=1.4386, val=1.0849, acc=0.7676
Epoch 26: train=1.4294, val=1.0272, acc=0.7799
Epoch 27: train=1.4362, val=1.0312, acc=0.7772
Epoch 28: train=1.4296, val=1.0816, acc=0.7684
Epoch 29: train=1.4110, val=1.0532, acc=0.7747
Epoch 30: train=1.4138, val=1.0436, acc=0.7765
Epoch 31: train=1.4030, val=1.0447, acc=0.7771
Seed: 2, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "mixup"}
Epoch 1: train=1.9456, val=1.5426, acc=0.5248
Epoch 2: train=1.8253, val=1.4526, acc=0.5736
Epoch 3: train=1.7684, val=1.3491, acc=0.6336
Epoch 4: train=1.7237, val=1.2999, acc=0.6590
Epoch 5: train=1.7056, val=1.2539, acc=0.6723
Epoch 6: train=1.6759, val=1.2243, acc=0.6945
Epoch 7: train=1.6553, val=1.1994, acc=0.7010
Epoch 8: train=1.6194, val=1.1647, acc=0.7212
Epoch 9: train=1.6089, val=1.1345, acc=0.7299
Epoch 10: train=1.5837, val=1.1359, acc=0.7354
Epoch 11: train=1.5805, val=1.1509, acc=0.7379
Epoch 12: train=1.5733, val=1.1066, acc=0.7445
Epoch 13: train=1.5521, val=1.1167, acc=0.7449
Epoch 14: train=1.5481, val=1.0751, acc=0.7589
Epoch 15: train=1.5426, val=1.0798, acc=0.7550
Epoch 16: train=1.5252, val=1.0881, acc=0.7494
Epoch 17: train=1.5089, val=1.0788, acc=0.7635
Epoch 18: train=1.5108, val=1.0829, acc=0.7635
Epoch 19: train=1.4993, val=1.0447, acc=0.7701
Epoch 20: train=1.4807, val=1.0836, acc=0.7665
Epoch 21: train=1.4700, val=1.0356, acc=0.7723
Epoch 22: train=1.4736, val=1.0734, acc=0.7676
Epoch 23: train=1.4542, val=1.0552, acc=0.7677
Epoch 24: train=1.4514, val=1.0686, acc=0.7689
Epoch 25: train=1.4447, val=1.0266, acc=0.7739
Epoch 26: train=1.4352, val=1.0573, acc=0.7754
Epoch 27: train=1.4333, val=1.0408, acc=0.7750
Epoch 28: train=1.4091, val=1.0359, acc=0.7758
Epoch 29: train=1.4111, val=1.0513, acc=0.7767
Epoch 30: train=1.4041, val=1.0497, acc=0.7762
Seed: 0, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "cutmix"}
Epoch 1: train=2.0073, val=1.6029, acc=0.4873
Epoch 2: train=1.8845, val=1.4507, acc=0.5686
Epoch 3: train=1.8288, val=1.3579, acc=0.6141
Epoch 4: train=1.7853, val=1.3082, acc=0.6400
Epoch 5: train=1.7563, val=1.2764, acc=0.6611
Epoch 6: train=1.7410, val=1.2506, acc=0.6720
Epoch 7: train=1.7096, val=1.2167, acc=0.6953
Epoch 8: train=1.6935, val=1.2005, acc=0.6957
Epoch 9: train=1.6837, val=1.1540, acc=0.7160
Epoch 10: train=1.6614, val=1.1530, acc=0.7174
Epoch 11: train=1.6502, val=1.1491, acc=0.7262
Epoch 12: train=1.6259, val=1.1447, acc=0.7304
Epoch 13: train=1.6224, val=1.1181, acc=0.7404
Epoch 14: train=1.6144, val=1.1004, acc=0.7379
Epoch 15: train=1.5986, val=1.0985, acc=0.7369
Epoch 16: train=1.5852, val=1.0660, acc=0.7560
Epoch 17: train=1.5796, val=1.0880, acc=0.7482
Epoch 18: train=1.5617, val=1.0391, acc=0.7622
Epoch 19: train=1.5529, val=1.0526, acc=0.7681
Epoch 20: train=1.5514, val=1.0516, acc=0.7623
Epoch 21: train=1.5336, val=1.0455, acc=0.7688
Epoch 22: train=1.5376, val=1.0626, acc=0.7613
Epoch 23: train=1.5287, val=1.0330, acc=0.7689
Epoch 24: train=1.5290, val=1.0470, acc=0.7636
Epoch 25: train=1.5042, val=1.0209, acc=0.7767
Epoch 26: train=1.5147, val=1.0463, acc=0.7654
Epoch 27: train=1.4984, val=1.0081, acc=0.7808
Epoch 28: train=1.4984, val=1.0086, acc=0.7816
Epoch 29: train=1.5056, val=1.0130, acc=0.7852
Epoch 30: train=1.4754, val=1.0082, acc=0.7796
Epoch 31: train=1.4775, val=0.9870, acc=0.7889
Epoch 32: train=1.4683, val=1.0018, acc=0.7867
Epoch 33: train=1.4675, val=0.9985, acc=0.7881
Epoch 34: train=1.4643, val=1.0074, acc=0.7891
Epoch 35: train=1.4669, val=1.0145, acc=0.7831
Epoch 36: train=1.4571, val=0.9892, acc=0.7858
Seed: 1, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "cutmix"}
Epoch 1: train=2.0050, val=1.5594, acc=0.5196
Epoch 2: train=1.8860, val=1.4691, acc=0.5586
Epoch 3: train=1.8340, val=1.3726, acc=0.6048
Epoch 4: train=1.8065, val=1.3292, acc=0.6309
Epoch 5: train=1.7680, val=1.2766, acc=0.6529
Epoch 6: train=1.7455, val=1.2515, acc=0.6704
Epoch 7: train=1.7185, val=1.2126, acc=0.6837
Epoch 8: train=1.7037, val=1.1988, acc=0.6972
Epoch 9: train=1.6893, val=1.1793, acc=0.7048
Epoch 10: train=1.6578, val=1.1681, acc=0.7026
Epoch 11: train=1.6584, val=1.1540, acc=0.7195
Epoch 12: train=1.6342, val=1.1091, acc=0.7317
Epoch 13: train=1.6332, val=1.1160, acc=0.7358
Epoch 14: train=1.6061, val=1.1093, acc=0.7391
Epoch 15: train=1.5984, val=1.1142, acc=0.7331
Epoch 16: train=1.5943, val=1.0849, acc=0.7511
Epoch 17: train=1.5794, val=1.0753, acc=0.7567
Epoch 18: train=1.5632, val=1.0666, acc=0.7605
Epoch 19: train=1.5706, val=1.0809, acc=0.7515
Epoch 20: train=1.5635, val=1.0571, acc=0.7633
Epoch 21: train=1.5462, val=1.0453, acc=0.7691
Epoch 22: train=1.5334, val=1.0519, acc=0.7665
Epoch 23: train=1.5262, val=1.0388, acc=0.7688
Epoch 24: train=1.5332, val=1.0349, acc=0.7714
Epoch 25: train=1.5196, val=1.0325, acc=0.7729
Epoch 26: train=1.5107, val=1.0284, acc=0.7765
Epoch 27: train=1.5105, val=1.0257, acc=0.7800
Epoch 28: train=1.5055, val=1.0364, acc=0.7775
Epoch 29: train=1.5141, val=1.0237, acc=0.7808
Epoch 30: train=1.4999, val=1.0246, acc=0.7814
Epoch 31: train=1.4964, val=1.0062, acc=0.7842
Epoch 32: train=1.4725, val=1.0008, acc=0.7875
Epoch 33: train=1.4703, val=0.9932, acc=0.7861
Epoch 34: train=1.4694, val=1.0064, acc=0.7867
Epoch 35: train=1.4696, val=1.0109, acc=0.7874
Epoch 36: train=1.4551, val=0.9950, acc=0.7878
Epoch 37: train=1.4568, val=0.9975, acc=0.7894
Epoch 38: train=1.4396, val=0.9873, acc=0.7928
Epoch 39: train=1.4432, val=0.9960, acc=0.7945
Epoch 40: train=1.4319, val=0.9864, acc=0.7939
Epoch 41: train=1.4377, val=0.9891, acc=0.7914
Epoch 42: train=1.4399, val=0.9883, acc=0.7923
Epoch 43: train=1.4338, val=0.9798, acc=0.7947
Epoch 44: train=1.4412, val=0.9913, acc=0.7929
Epoch 45: train=1.4274, val=0.9766, acc=0.7958
Epoch 46: train=1.4232, val=0.9757, acc=0.7942
Epoch 47: train=1.4160, val=0.9800, acc=0.7944
Epoch 48: train=1.4122, val=0.9872, acc=0.7964
Epoch 49: train=1.4041, val=0.9836, acc=0.7956
Epoch 50: train=1.4083, val=0.9749, acc=0.7959
Epoch 51: train=1.3937, val=0.9758, acc=0.7990
Epoch 52: train=1.3897, val=0.9830, acc=0.7957
Epoch 53: train=1.3965, val=0.9825, acc=0.7985
Epoch 54: train=1.3978, val=0.9849, acc=0.7975
Epoch 55: train=1.3832, val=0.9859, acc=0.7991
Seed: 2, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "cutmix"}
Epoch 1: train=1.9952, val=1.5410, acc=0.5236
Epoch 2: train=1.8765, val=1.4622, acc=0.5841
Epoch 3: train=1.8385, val=1.4124, acc=0.5852
Epoch 4: train=1.7977, val=1.3393, acc=0.6250
Epoch 5: train=1.7632, val=1.2951, acc=0.6403
Epoch 6: train=1.7494, val=1.2434, acc=0.6742
Epoch 7: train=1.7224, val=1.2564, acc=0.6616
Epoch 8: train=1.6975, val=1.2105, acc=0.6801
Epoch 9: train=1.6727, val=1.1762, acc=0.7042
Epoch 10: train=1.6601, val=1.1533, acc=0.7180
Epoch 11: train=1.6405, val=1.1291, acc=0.7236
Epoch 12: train=1.6411, val=1.1395, acc=0.7276
Epoch 13: train=1.6181, val=1.1162, acc=0.7390
Epoch 14: train=1.6133, val=1.1054, acc=0.7335
Epoch 15: train=1.5988, val=1.0952, acc=0.7457
Epoch 16: train=1.5867, val=1.0743, acc=0.7524
Epoch 17: train=1.5721, val=1.0683, acc=0.7548
Epoch 18: train=1.5729, val=1.0567, acc=0.7581
Epoch 19: train=1.5600, val=1.0767, acc=0.7626
Epoch 20: train=1.5495, val=1.0510, acc=0.7651
Epoch 21: train=1.5374, val=1.0378, acc=0.7710
Epoch 22: train=1.5255, val=1.0475, acc=0.7722
Epoch 23: train=1.5275, val=1.0272, acc=0.7762
Epoch 24: train=1.5207, val=1.0411, acc=0.7714
Epoch 25: train=1.5133, val=1.0137, acc=0.7793
Epoch 26: train=1.5042, val=1.0240, acc=0.7742
Epoch 27: train=1.5037, val=1.0262, acc=0.7756
Epoch 28: train=1.5011, val=1.0091, acc=0.7830
Epoch 29: train=1.4896, val=1.0037, acc=0.7833
Epoch 30: train=1.4843, val=1.0073, acc=0.7831
Epoch 31: train=1.4930, val=1.0176, acc=0.7829
Epoch 32: train=1.4745, val=1.0065, acc=0.7875
Epoch 33: train=1.4555, val=0.9869, acc=0.7909
Epoch 34: train=1.4611, val=0.9964, acc=0.7900
Epoch 35: train=1.4559, val=1.0102, acc=0.7873
Epoch 36: train=1.4643, val=0.9915, acc=0.7883
Epoch 37: train=1.4592, val=1.0126, acc=0.7873
Epoch 38: train=1.4408, val=0.9927, acc=0.7917
Seed: 0, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "both"}
Epoch 1: train=1.9791, val=1.5849, acc=0.5111
Epoch 2: train=1.8601, val=1.4273, acc=0.5970
Epoch 3: train=1.8061, val=1.3972, acc=0.6103
Epoch 4: train=1.7777, val=1.2926, acc=0.6517
Epoch 5: train=1.7481, val=1.2779, acc=0.6680
Epoch 6: train=1.7270, val=1.2257, acc=0.6870
Epoch 7: train=1.7003, val=1.2080, acc=0.7077
Epoch 8: train=1.6841, val=1.1733, acc=0.7089
Epoch 9: train=1.6726, val=1.1522, acc=0.7228
Epoch 10: train=1.6518, val=1.1329, acc=0.7316
Epoch 11: train=1.6467, val=1.1212, acc=0.7346
Epoch 12: train=1.6203, val=1.1126, acc=0.7403
Epoch 13: train=1.6132, val=1.1101, acc=0.7449
Epoch 14: train=1.5932, val=1.1065, acc=0.7493
Epoch 15: train=1.5954, val=1.0952, acc=0.7501
Epoch 16: train=1.5799, val=1.0461, acc=0.7635
Epoch 17: train=1.5746, val=1.1212, acc=0.7466
Epoch 18: train=1.5683, val=1.0693, acc=0.7647
Epoch 19: train=1.5515, val=1.0722, acc=0.7640
Epoch 20: train=1.5508, val=1.0436, acc=0.7737
Epoch 21: train=1.5487, val=1.0356, acc=0.7755
Epoch 22: train=1.5348, val=1.0541, acc=0.7694
Epoch 23: train=1.5273, val=1.0559, acc=0.7701
Epoch 24: train=1.5132, val=1.0282, acc=0.7761
Epoch 25: train=1.5107, val=1.0361, acc=0.7824
Epoch 26: train=1.5138, val=1.0371, acc=0.7755
Epoch 27: train=1.5108, val=1.0205, acc=0.7831
Epoch 28: train=1.4980, val=0.9967, acc=0.7871
Epoch 29: train=1.4956, val=1.0219, acc=0.7859
Epoch 30: train=1.4831, val=1.0052, acc=0.7860
Epoch 31: train=1.4810, val=0.9958, acc=0.7908
Epoch 32: train=1.4831, val=1.0107, acc=0.7880
Epoch 33: train=1.4649, val=1.0007, acc=0.7908
Epoch 34: train=1.4599, val=0.9932, acc=0.7913
Epoch 35: train=1.4436, val=1.0232, acc=0.7900
Epoch 36: train=1.4537, val=0.9969, acc=0.7895
Epoch 37: train=1.4414, val=0.9918, acc=0.7927
Epoch 38: train=1.4478, val=1.0183, acc=0.7917
Epoch 39: train=1.4414, val=1.0158, acc=0.7906
Epoch 40: train=1.4404, val=0.9921, acc=0.7956
Epoch 41: train=1.4377, val=1.0103, acc=0.7937
Epoch 42: train=1.4295, val=1.0087, acc=0.7927
Seed: 1, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "both"}
Epoch 1: train=1.9849, val=1.5567, acc=0.5347
Epoch 2: train=1.8678, val=1.4577, acc=0.5685
Epoch 3: train=1.8194, val=1.3613, acc=0.6103
Epoch 4: train=1.7809, val=1.3281, acc=0.6494
Epoch 5: train=1.7559, val=1.2518, acc=0.6768
Epoch 6: train=1.7246, val=1.2347, acc=0.6785
Epoch 7: train=1.7095, val=1.2516, acc=0.6838
Epoch 8: train=1.6785, val=1.2083, acc=0.7114
Epoch 9: train=1.6711, val=1.2201, acc=0.7034
Epoch 10: train=1.6479, val=1.1481, acc=0.7244
Epoch 11: train=1.6404, val=1.1467, acc=0.7249
Epoch 12: train=1.6213, val=1.1165, acc=0.7435
Epoch 13: train=1.6102, val=1.1052, acc=0.7501
Epoch 14: train=1.5956, val=1.0875, acc=0.7534
Epoch 15: train=1.5951, val=1.1011, acc=0.7526
Epoch 16: train=1.5793, val=1.0681, acc=0.7632
Epoch 17: train=1.5849, val=1.0855, acc=0.7596
Epoch 18: train=1.5686, val=1.0655, acc=0.7650
Epoch 19: train=1.5601, val=1.0773, acc=0.7626
Epoch 20: train=1.5510, val=1.0506, acc=0.7723
Epoch 21: train=1.5373, val=1.0317, acc=0.7718
Epoch 22: train=1.5373, val=1.0429, acc=0.7738
Epoch 23: train=1.5203, val=1.0317, acc=0.7769
Epoch 24: train=1.5166, val=1.0244, acc=0.7809
Epoch 25: train=1.5169, val=1.0291, acc=0.7826
Epoch 26: train=1.4831, val=1.0310, acc=0.7831
Epoch 27: train=1.4999, val=1.0059, acc=0.7849
Epoch 28: train=1.5031, val=1.0389, acc=0.7760
Epoch 29: train=1.4948, val=1.0109, acc=0.7855
Epoch 30: train=1.4786, val=1.0180, acc=0.7864
Epoch 31: train=1.4851, val=1.0167, acc=0.7874
Epoch 32: train=1.4729, val=1.0110, acc=0.7899
Seed: 2, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": false, "mix_type": "both"}
Epoch 1: train=1.9773, val=1.5483, acc=0.5236
Epoch 2: train=1.8556, val=1.4350, acc=0.5833
Epoch 3: train=1.8122, val=1.3677, acc=0.6206
Epoch 4: train=1.7796, val=1.3173, acc=0.6562
Epoch 5: train=1.7375, val=1.2772, acc=0.6564
Epoch 6: train=1.7118, val=1.2137, acc=0.6875
Epoch 7: train=1.7029, val=1.1963, acc=0.6953
Epoch 8: train=1.6716, val=1.1639, acc=0.7069
Epoch 9: train=1.6753, val=1.1573, acc=0.7256
Epoch 10: train=1.6458, val=1.1363, acc=0.7349
Epoch 11: train=1.6204, val=1.1335, acc=0.7369
Epoch 12: train=1.6295, val=1.1072, acc=0.7447
Epoch 13: train=1.6062, val=1.1340, acc=0.7425
Epoch 14: train=1.6038, val=1.0989, acc=0.7462
Epoch 15: train=1.5847, val=1.1189, acc=0.7505
Epoch 16: train=1.5740, val=1.0998, acc=0.7525
Epoch 17: train=1.5688, val=1.0631, acc=0.7599
Epoch 18: train=1.5561, val=1.0604, acc=0.7659
Epoch 19: train=1.5414, val=1.0328, acc=0.7739
Epoch 20: train=1.5343, val=1.0718, acc=0.7730
Epoch 21: train=1.5378, val=1.0473, acc=0.7772
Epoch 22: train=1.5331, val=1.0209, acc=0.7792
Epoch 23: train=1.5220, val=1.0424, acc=0.7812
Epoch 24: train=1.5229, val=1.0193, acc=0.7844
Epoch 25: train=1.4966, val=1.0078, acc=0.7853
Epoch 26: train=1.4995, val=1.0204, acc=0.7804
Epoch 27: train=1.4886, val=1.0081, acc=0.7854
Epoch 28: train=1.5056, val=1.0107, acc=0.7850
Epoch 29: train=1.4795, val=1.0132, acc=0.7878
Epoch 30: train=1.4862, val=1.0206, acc=0.7896
Seed: 0, Config: {"model": "cnn", "lr": 0.00046082521043368826, "weight_decay": 3.600654215799517e-05, "dropout": 0.3, "batch_size": 64, "augmentation": true, "mix_type": null}
Epoch 1: train=1.8049, val=1.5503, acc=0.5046
Epoch 2: train=1.5690, val=1.3907, acc=0.5930
Epoch 3: train=1.4706, val=1.3265, acc=0.6209
Epoch 4: train=1.4013, val=1.2578, acc=0.6588
Epoch 5: train=1.3511, val=1.2253, acc=0.6733